#!/bin/bash

function cleanup()
{
echo "Cleaning up..."
rm -rvf minecraftspigot2
}

trap cleanup EXIT



read -p "Server Version: " VER

RED="\033[1;31m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
BLUE="̣̣\033[0;34m"
NC="\033[0m" # No Color

#no Ctrl-C allowed. here
trap "" SIGINT


if [ -f "minecraftspigot/eula.txt" ];
then
   echo -e "${GREEN}[+] Old Server found at $PWD/minecraftspigot ${NC}"

   else

   echo -e "${RED}[-] Old Server not found!${NC}" && exit 1
fi




echo -e "${YELLOW}[I] Getting new Server Version${NC}"

echo -e "${YELLOW}[I] This is gonna take a while${NC}"


mkdir minecraftspigot2 && cd minecraftspigot2

wget -q https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar >> /dev/null

echo -e "${YELLOW}[I] Building up server${NC}"
echo "------------------------------Building Proccess------------------------------------"
java -jar BuildTools.jar --rev $VER >> /dev/null
echo "------------------------------Building Proccess------------------------------------"

echo -e "${YELLOW}[I] Creating Eula file...${NC}"
echo -e "${RED}[W] By Creating this eula you accept to the official Eula: https://www.minecraft.net/en-us/eula${NC}"
touch eula.txt
date=$(date "+%D %T")
echo "#EULA generated by MSTK script at $date" >> eula.txt
echo eula=true >> eula.txt


echo -e "${GREEN}[+] Done setting up New server${NC}"



cd ../minecraftspigot2

echo -e "${YELLOW}[I] Cleaning up temporary files...${NC}"
rm -rf BuildTools.jar BuildTools.log.txt


echo -e "${YELLOW}[I] Cloning old server files into new ones...${NC}"
cd ../minecraftspigot
cp -r server.properties world/ world_nether/ world_the_end/ ops.json whitelist.json banned-ips.json banned-players.json plugins/ start1.sh wepif.yml logs/ ../minecraftspigot2


echo -e "${YELLOW}[I] Deleting the old server...${NC}"
cd ..
rm -rf minecraftspigot


echo -e "${YELLOW}[I] Renaming the new server to minecraftspigot....${NC}"
mv minecraftspigot2 minecraftspigot



echo -e "${GREEN}[+] Done. Check if any errors ocurred. ${NC}"
