#!/bin/bash

function cleanup()
{
echo "Cleaning up..."
rm -rvf $1
}

trap cleanup EXIT


sleep 1


RED="\033[1;31m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
BLUE="̣̣\033[0;34m"
NC="\033[0m" # No Color


echo -e "${GREEN}[+] Started MSTK creator!${NC}"
sleep 0.5
echo -e "${RED}[W] STILL IN ALPHA VERSION!${NC}"
sleep 1
clear


#--------------------------------------------------------INFO GATHERING---------------------
echo -e "${BLUE}[?] NEW Server Name:${NC}"
echo -e "${YELLOW}[W] is gonna Spawn in $PWD.${NC}"
read NS

clear

echo -e "${BLUE}[?] NEW Server Type:${NC}"
echo "Spigot, Vanilla"
read ST

clear




if [ $ST == Spigot ]; then
echo -e "${BLUE}[?] NEW Server Version:${NC}"
read SV
fi

sleep 2
clear
sleep 0.5
#-------------------------------------------------ASK IF CORRECT------------------

echo -e "${BLUE}[?] Is this correct?${NC}"
echo "NEW Server: $NS"
echo "NEW Server Type: $ST"

if [ $ST == Spigot ]; then
echo "Spigot Server Version: $SV"
fi

echo
echo -e "${RED}(Y/N) ${NC}"
read ok
#---------------------------------------------------ACTUAL UPDATE---------------
sleep 1
clear

case $ok in
 N|n) echo ABORT && exit 1 ;;
 Y|y) echo -e "${GREEN}[+] OK, Starting update...${NC}" ;;
esac


#--------------------------------------------------------ACTUAL UPDATE---------------------




# Run something important, no Ctrl-C allowed.
trap "" SIGINT


echo -e "${YELLOW}[I] Getting new Server Version${NC}"
sleep 0.5
echo -e "${YELLOW}[I] This is gonna take a while${NC}"
sleep 1
echo ---------------------------------------------------------------------------------
mkdir $NS && cd $NS

case $ST in
 Spigot) wget -q https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar ;;
Vanilla) wget -q https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar      ;;
*      ) echo -e "${RED}[-] Unknown new server type.${NC}" && cleanup $NS ;;
esac

case $ST in
 Spigot) java -jar BuildTools.jar --rev $SV >> /dev/null;;
Vanilla) echo -e "${GREEN}[I]To build up the Server, Please run ¨java -jar server.jar¨"
esac



echo ---------------------------------------------------------------------------------
echo -e "${YELLOW}[I] Creating Eula file...${NC}"
echo -e "${RED}[W] By Creating this eula you accept to the official Minecraft Eula: https://www.minecraft.net/en-us/eula${NC}"
date=$(date "+%D %T")
touch eula.txt
echo "#EULA generated by MSTK script at $date" >> eula.txt
echo eula=true >> eula.txt


echo -e "${GREEN}[+] Done. Check if any errors ocurred."${NC}
