#!/bin/bash

function cleanup()
{
echo "Cleaning up..."
rm -rvf $1
}

trap cleanup EXIT

sleep 1


RED="\033[1;31m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
BLUE="̣̣\033[0;34m"
NC="\033[0m" # No Color

#--------------------------------------------------------INFO GATHERING---------------------
echo -e "${GREEN}[+] Started MSTK updater!${NC}"
sleep 0.5
echo -e "${RED}[W] STILL IN ALPHA VERSION!${NC}"
sleep 1
clear



echo -e "${BLUE}[?] OLD Server Name:${NC}"
echo -e "${YELLOW}[W] Has to be in $PWD.${NC}"
read OS



echo -e "${BLUE}[?] NEW Server Name:${NC}"
echo -e "${YELLOW}[W] is gonna Spawn in $PWD.${NC}"
read NS




echo -e "${BLUE}[?] OLD Server Type:${NC}"
echo "Spigot, Vanilla"
read OST



echo -e "${BLUE}[?] NEW Server Type:${NC}"
echo "Spigot, Vanilla"
read NST



if [ $NST == Spigot ]; then
echo -e "${BLUE}[?] NEW Server Version:${NC}"
read NSV
fi

sleep 2
clear
sleep 0.5
#------------------------------ASK IF CORRECTLY TYPED-----------------------------------------


echo -e "${BLUE}[?] Is this correct?${NC}"
echo "OLD Server: $OS"
echo "NEW Server: $NS"
echo "OLD Server type: $OST"
echo "NEW Server Type: $NST"

if [ $NST == Spigot ]; then
echo "Spigot Server Version: $NSV"

fi
echo -e "${RED}(Y/N) ${NC}"
read ok

sleep 1
clear

case $ok in
 N|n) echo ABORT && exit 1 ;;
 Y|y) echo -e "${GREEN}[+] OK, Starting update...${NC}" ;;
esac

#--------------------------------------------------------ACTUAL UPDATE---------------------
#no Ctrl-C allowed. here
trap "" SIGINT


if [ -f "$OS/eula.txt" ];
then
   echo -e "${GREEN}[+] Old Server found at $PWD/$OS ${NC}"

   else

   echo -e "${RED}[-] Old Server not found!${NC}" && exit 1
fi

sleep 1


echo -e "${YELLOW}[I] Building new Server Version${NC}"
sleep 0.5
echo -e "${YELLOW}[I] This is gonna take a while${NC}"
sleep 1
echo ---------------------------------------------------------------------------------
mkdir $NS && cd $NS

case $NST in
 Spigot) wget -q https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar >> /dev/null;;
Vanilla) wget -q https://piston-data.mojang.com/v1/objects/5b868151bd02b41319f54c8d4061b8cae84e665c/server.jar  >> /dev/null    ;;
*      )echo -e "${RED}[-] Unknown new server type:$NST ${NC}" && cleanup $NS  >> /dev/null                        ;;
esac


case $NST in
 Spigot) java -jar BuildTools.jar --rev $NSV >> /dev/null ;;
Vanilla) echo -e "${YELLOW}[I] To build up the Server, Please run ¨java -jar server.jar¨${NC}" ;;
esac

echo ---------------------------------------------------------------------------------

echo -e "${YELLOW}[I] Creating Eula file...${NC}"
echo -e "${RED}[W] By Creating this eula you accept to the official Eula: https://www.minecraft.net/en-us/eula${NC}"
touch eula.txt
date=$(date "+%D %T")
echo "#EULA generated by MSTK script at $date" >> eula.txt
echo eula=true >> eula.txt
sleep 0.2

echo -e "${GREEN}[+] Done setting up New server${NC}"
sleep 1

echo -e "${YELLOW}[I] Now Copying old server files into new ones...${NC}"

cd ../$OS
case $OST in
Vanilla)
cp -r server.properties world/ ops.json whitelist.json banned-ips.json banned-players.json ../$NS;;

Spigot)
cp -r server.properties world/ world_nether/ world_the_end/ ops.json whitelist.json banned-ips.json banned-players.json plugins/ ../$NS;;
esac


echo -e "${GREEN}[+] Done. Check if any errors ocurred.${NC}"
sleep 1
